### PR TITLE
Prefix header include

### PR DESCRIPTION
**Pull request by radarhere**
Another one for https://github.com/python-pillow/Pillow/pull/4923

### CODE REVIEW

**Comment by hugovk** [comment]
@ax3l Thoughts on this? We can then get https://github.com/python-pillow/Pillow/pull/4923 merged for this week's Pillow 8.0.0 release.

**Comment by hugovk** [comment]
@radarhere Would you like to update PR https://github.com/python-pillow/Pillow/pull/4923 directly?

**Comment by ax3l** [comment]
Thanks, wow did not know you can merge this :)

**Comment by ax3l** [comment]
Thank you for the update!

**Pull request merged**
